CREATE TABLE `affiliateLinks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int,
	`propertyId` int,
	`affiliateUrl` varchar(500) NOT NULL,
	`affiliateNetwork` varchar(100),
	`commissionPercentage` int NOT NULL,
	`clicks` int NOT NULL DEFAULT 0,
	`conversions` int NOT NULL DEFAULT 0,
	`revenue` int NOT NULL DEFAULT 0,
	`revenueUsd` int NOT NULL DEFAULT 0,
	`active` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `affiliateLinks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `eventBookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int NOT NULL,
	`userId` int,
	`guestName` varchar(255) NOT NULL,
	`guestEmail` varchar(320) NOT NULL,
	`guestPhone` varchar(50),
	`numberOfGuests` int NOT NULL DEFAULT 1,
	`totalPrice` int,
	`totalPriceUsd` int,
	`commissionAmount` int,
	`commissionAmountUsd` int,
	`affiliateLinkUsed` int NOT NULL DEFAULT 0,
	`status` enum('pending','confirmed','completed','cancelled') NOT NULL DEFAULT 'pending',
	`bookingReference` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `eventBookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `eventBookings_bookingReference_unique` UNIQUE(`bookingReference`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleTh` varchar(255),
	`description` text,
	`descriptionTh` text,
	`category` varchar(100) NOT NULL,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`location` text,
	`locationTh` text,
	`latitude` varchar(50),
	`longitude` varchar(50),
	`price` int,
	`priceUsd` int,
	`organizer` varchar(255),
	`organizerPhone` varchar(50),
	`organizerEmail` varchar(320),
	`youtubeUrl` varchar(500),
	`affiliateLink` varchar(500),
	`source` enum('visitsamroiyot','partner','internal') NOT NULL DEFAULT 'internal',
	`sourceId` varchar(255),
	`commissionRate` int NOT NULL DEFAULT 25,
	`bookingUrl` varchar(500),
	`published` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastScrapedAt` timestamp,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
