CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`firstName` varchar(100),
	`interestLevel` enum('casual_visitor','serious_buyer','investor') NOT NULL DEFAULT 'casual_visitor',
	`unsubscribed` int NOT NULL DEFAULT 0,
	`unsubscribeToken` varchar(255),
	`email1Sent` timestamp,
	`email1Opened` int NOT NULL DEFAULT 0,
	`email1Clicked` int NOT NULL DEFAULT 0,
	`email2Sent` timestamp,
	`email2Opened` int NOT NULL DEFAULT 0,
	`email2Clicked` int NOT NULL DEFAULT 0,
	`email3Sent` timestamp,
	`email3Opened` int NOT NULL DEFAULT 0,
	`email3Clicked` int NOT NULL DEFAULT 0,
	`email4Sent` timestamp,
	`email4Opened` int NOT NULL DEFAULT 0,
	`email4Clicked` int NOT NULL DEFAULT 0,
	`youtubeClicked` int NOT NULL DEFAULT 0,
	`propertyInquirySubmitted` int NOT NULL DEFAULT 0,
	`affiliateLinkClicked` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_email_unique` UNIQUE(`email`),
	CONSTRAINT `leads_unsubscribeToken_unique` UNIQUE(`unsubscribeToken`)
);
